# Site settings
name: Byeon JI Yeon
description: "60th ROTC on 163 🇰🇷 AND GWNU 20181716"
url: ""

facebook_username: profile.php?id=100008056174846
instagram_username:  by.j_y__n
blog_url: "https://blog.naver.com/elzelzz"
email: elzelz@gwnu.ac.kr

avatar: yes
avatar_img_path: "imgs/byeonji.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"



favicon_img: yes
favicon_img_path: "imgs/favicon.ico"


markdown: kramdown
permalink: pretty
